#!/bin/bash

# ----------------------------------Function to execute a MySQL query
execute_query_mysql() {
    local query="$1"
    mysql  -D "$MYSQL_DB" -e "$query"
}

# --------------------------------------enter data
read -p "Enter MySQL database name: " MYSQL_DB


# ----------------------------------Export script for use in other scripts
export MYSQL_DB

# ---------------------------------to connect to MySQL
connect_to_mysql() {
    local query="$1"
    mysql  -D "$MYSQL_DB" -e "$query"
}

query="SHOW TABLES;"
connect_to_mysql "$query"

# ----------------------------------------show tables
connect_to_mysql "USE $MYSQL_DB; SHOW TABLES;"

# ----------------------------------------Check if connection was successful
if [ $? -eq 0 ]; then
    echo "You Connected To $MYSQL_DB Successfully"
else
    echo "Failed to connect to $MYSQL_DB"
fi
