#!/bin/bash

#-----------------------------------------------------------------------------
# MySQL login details

MYSQL_USER="root"

MYSQL_HOST="localhost"

#-----------------------------------------------------------------------------
# Function to execute a MySQL query and print the results

execute_query() {
    local query="$1"
    local database="$2"

    mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -h "$MYSQL_HOST" "$database" -e "$query"
}

#-----------------------------------------------------------------------------
# Function to create a new database

create_database() {
    local database
    read -p "Enter the name of the new database: " database
    
    execute_query "CREATE DATABASE IF NOT EXISTS $database" ""
    
    if [ $? -eq 0 ]; then
        echo "Database '$database' created successfully."
    else
        echo "Failed to create database '$database'."
    fi
}

create_database