#!/bin/bash

echo "Connected To Server Please Choose From Options"


    select choice in "Create Database" "List Databases" "Connect To Databases" "Drop Database" "Exit"; do
        case $choice in
        "Create Database") . ./createdata ;;
        "List Databases") . ./listdata ;;
        "Connect To Databases") . ./connecttodata ;;
        "Drop Database") . ./dropdata ;;
        "Exit") echo "Exit Main Menu" ; break ;;
        *) echo $REPLY is not one of the choices. ;;
        esac
    done